#! /bin/sh

GCJ=gcj-3.0

echo -n "Compiling vecmath... "
if test -r libvecmath.so
then
    echo "skipped"
else
    cd vecmath; make -f Makefile.gcj lib
    mv vecmath/libvecmath.so .
fi

echo -n "Compiling gnujaxp... "
if test -r libgnujaxp.so
then
    echo "skipped"
else
    if ${GCJ} -shared -o libgnujaxp.so ../jar/gnujaxp.jar
    then
        echo "done"
    else
        echo "failed"
    fi
fi

# this gives several warning, but succeeds

echo -n "Compiling xerces... "
if test -r libxerces.so
then
    echo "skipped"
else
    if ${GCJ} -shared -o libxerces.so ../jar/xerces-1.3.0.jar
    then
        echo "done"
    else
        echo "failed"
    fi
fi

exit 0;

# the rest fails

echo -n "Compiling log4j... "
if test -r liblogjcore.so
then
    echo "skipped"
else
    if ${GCJ} -shared -o liblogj.so ../jar/log4j.jar && \
       ${GCJ} -shared -o liblogjcore.so ../jar/log4j-core.jar
    then
        echo "done"
    else
        echo "failed"
    fi
fi
