#! /bin/sh

GCJ=gcj-3.0

CDKLIBDIR="../jar"
CDKSRCDIR="../src"
CDKBUILDDIR="../gcj/build"
JARLIBS=`ls -1 $CDKLIBDIR/*.jar | perl -ne "s/\n|\r/:/g; print;"`

LIBRARIES="-L. "

# Apply patches to work around some problems
mkdir -p src/org/openscience/cdk/tools
cp ../src/org/openscience/cdk/tools/LoggingTool.java src/org/openscience/cdk/tools/.
patch src/org/openscience/cdk/tools/LoggingTool.java patches/org.openscience.cdk.tools.LoggingTool.java
cp ../src/org/openscience/cdk/tools/IsotopeFactory.java src/org/openscience/cdk/tools/.
patch src/org/openscience/cdk/tools/IsotopeFactory.java patches/org.openscience.cdk.tools.IsotopeFactory.java

# Compile .so libraries
for lib in core extra
do
    echo "Compiling ${lib} library..."
    OPTIONS="-shared -I${CDKSRCDIR} ${LIBRARIES} --CLASSPATH=$JARLIBS"
    CLASSES=`./list-classes ${lib}.classes`
    if test -r libcdk${lib}.so
    then
        echo "skipped"
    else
        echo "  command: $GCJ $OPTIONS ${CLASSES} -o libcdk${lib}.so"
        if ! $GCJ $OPTIONS ${CLASSES} -o libcdk${lib}.so
        then
            echo "Error during compilation of ${lib} library!"
            exit 1
        fi
    fi
    LIBRARIES="${LIBRARIES} -lcdk${lib}"
done

# Compile viewer application
echo "Compiling cdk-fileconvertor application..."
OPTIONS="-I${CDKSRCDIR} ${LIBRARIES} --CLASSPATH=$JARLIBS"
CLASSES="../src/org/openscience/cdk/applications/FileConvertor.java"
LIBRARIES="${LIBRARIES} -lvecmath -lgnujaxp -lxerces"
echo "  command: $GCJ ${LIBRARIES} $OPTIONS ${CLASSES} -o cdk-fileconvertor"
$GCJ ${LIBRARIES} $OPTIONS ${CLASSES} --main=org.openscience.cdk.applications.FileConvertor -o cdk-fileconvertor
