#! /bin/sh

GCJ=gcj-3.0

CDKLIBDIR="../jar"
CDKSRCDIR="../src"
CDKBUILDDIR="../gcj/build"
JARLIBS=`ls -1 $CDKLIBDIR/*.jar | perl -ne "s/\n|\r/:/g; print;"`

LIBRARIES="-L. "

# Compile .so libraries
for lib in core extra
do
    echo "Compiling ${lib} library..."
    OPTIONS="-shared -I${CDKSRCDIR} ${LIBRARIES} --CLASSPATH=$JARLIBS"
    CLASSES=`./list-classes ${lib}.classes`
    echo "  command: $GCJ $OPTIONS ${CLASSES} -o libcdk${lib}.so"
    if ! $GCJ $OPTIONS ${CLASSES} -o libcdk${lib}.so
    then
        echo "Error during compilation of ${lib} library!"
        exit 1
    fi
    LIBRARIES="${LIBRARIES} -lcdk${lib}"
done

# Compile viewer application
echo "Compiling cdk-fileconvertor application..."
OPTIONS="-I${CDKSRCDIR} ${LIBRARIES} --CLASSPATH=$JARLIBS"
CLASSES="../src/org/openscience/cdk/applications/FileConvertor.java"
echo "  command: $GCJ $OPTIONS ${CLASSES} -o cdk-fileconvertor"
$GCJ $OPTIONS ${CLASSES} -o cdk-fileconvertor
