#! /usr/bin/perl
use diagnostics;
use strict;

my $CDKSRCDIR = "../src";
my $PATCHEDSRCDIR = "src";

if (!$ARGV[0]) {
    print "syntax: list-classes <classlist>\n";
    exit(1);
}

open(CLASSES, "<$ARGV[0]");
while (<CLASSES>) {
    if (/^\s*\#/) {
        # skip comment line
    } elsif (/^~/) {
        s/~//g;
        s/\./\//g;
        s/[\n|\r]//;
        print "$PATCHEDSRCDIR/";
        print;
        print ".java\n";
    } else {
        s/\./\//g;
        s/[\n|\r]//;
        print "$CDKSRCDIR/";
        print;
        print ".java\n";
    }
}
