# Rajarshi Guha <rajarshi@presidency.com>
# 06/08/2006

genstubs <- function(obj, fileName='stubs.java', verbose=FALSE) {
  cat( 'Currently does not generate stubs for \'call\' and \'formula\' objects\n' )
  nms <- sort(names(obj))
  
  fcon <- file(description = fileName, 'w')
  writeLines("// Autogenerated code: assumes that 'modelObject' is ", fcon)
  writeLines("// a RList object\n\n", fcon)
  attach(obj)
  for (nm in nms) {
    value <- get(nm)
    retType <- genReturnType(value)
    if (retType[1] == '') next

    rexpMethod = retType[2]
    retType <- retType[1]
    methodName = genMethodName(nm)

    comment <- paste('/**\n * Gets the <code>', nm, '</code> field of an <code>\'',
                     class(obj), '\'</code> object.\n *\n * @return The value of the ',
                     nm, ' field\n */\n', sep='', collapse='') 
    prefix <- paste('public ', retType, ' ', methodName, '()', collapse='', sep='')
    prefix <- paste(prefix, ' {\n', '    return modelObject.at(\"', nm, '\").', rexpMethod, ';\n}\n', sep='', collapse='')

    txt <- paste(comment, prefix, sep='', collapse='')
    writeLines(txt, con=fcon)
    
    if (verbose) cat(txt, '\n')
  }
  close(fcon)
  detach(obj)
}

genMethodName <- function(name) {

  # capitalize
  firstChar <- substr(name, 1,1)
  if (firstChar %in% letters)
    firstChar <- LETTERS[ which(letters == firstChar) ]
  substr(name,1,1) <- firstChar

  # remove '.' and capitalize
  tmp <- strsplit(name, '')[[1]]
  afterDot <- which(tmp == '.')+1
  for (i in afterDot) {
    if (tmp[i] %in% letters) {
      substr(name, i,i) <- LETTERS[ which(letters == tmp[i]) ]
    }
  }
  name <- gsub('\\.', '', name)

  paste('get',name, sep='', collapse='')
}

genReturnType <- function(obj) {
  varMode <- mode(obj)
  varClass <- class(obj)  
  varType <- typeof(obj)
  if (varMode == 'numeric') {
    if (varClass == 'matrix') {
      return(c('double[][]', 'asDoubleMatrix()'))
    }
    if (varType == 'integer' && length(obj) == 1) {
      return(c('int', 'asInt()'))
    }
    if (varType == 'integer' && length(obj) > 1) {
      return(c('int[]', 'asIntArray()'))
    }
    if (varType == 'double' && length(obj) == 1) {
      return(c('double', 'asDouble()'))
    } else {
      return(c('double[]', 'asDoubleArray()'))
    }
  } else if (varMode == 'factor') return(c('RFactor', 'asFactor()'))
  else if (varMode == 'list') return(c('RList', 'asList()'))
  else if (varMode == 'logical') return(c('RBool', 'asBool()'))
  else return(c('', ''))
}

