all: JavaDocStats.class KeywordTaglet.class

JavaDocStats.class: source/JavaDocStats.java
	javac -classpath /usr/local/j2sdk1.4.0/lib/tools.jar -d . -O source/JavaDocStats.java

KeywordTaglet.class: source/KeywordTaglet.java
	javac -classpath /usr/local/j2sdk1.4.0/lib/tools.jar -d . -O source/KeywordTaglet.java
