/* Generated By:JJTree: Do not edit this line. ASTAnyAtom.java */

package org.openscience.cdk.smiles.smarts.parser;

public class ASTAnyAtom extends SimpleNode {
  public ASTAnyAtom(int id) {
    super(id);
  }

  public ASTAnyAtom(SMARTSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SMARTSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
