/* Generated By:JJTree: Do not edit this line. ASTAliphatic.java */

package org.openscience.cdk.smiles.smarts.parser;

public class ASTAliphatic extends SimpleNode {
  public ASTAliphatic(int id) {
    super(id);
  }

  public ASTAliphatic(SMARTSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SMARTSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
