/* Generated By:JJTree: Do not edit this line. ASTBond.java */

package org.openscience.cdk.smiles.smarts.parser;

public class ASTBond extends SimpleNode {
    private double bondOrder;

    private int bondType;

    public int getBondType() {
        return bondType;
    }

    public void setBondType(int bondType) {
        this.bondType = bondType;
    }

    public double getBondOrder() {
        return bondOrder;
    }

    public void setBondOrder(double bondOrder) {
        this.bondOrder = bondOrder;
    }

    public ASTBond(int id) {
        super(id);
    }

    public ASTBond(SMARTSParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. * */
    public Object jjtAccept(SMARTSParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
