/* Generated By:JJTree: Do not edit this line. ASTDegree.java */

package org.openscience.cdk.smiles.smarts.parser;

public class ASTDegree extends SimpleNode {
    private int degree;

    public int getDegree() {
        return degree;
    }

    public void setDegree(int degree) {
        this.degree = degree;
    }

    public ASTDegree(int id) {
        super(id);
    }

    public ASTDegree(SMARTSParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. * */
    public Object jjtAccept(SMARTSParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
