/* Generated By:JJTree: Do not edit this line. ASTElement.java */

package org.openscience.cdk.smiles.smarts.parser;

public class ASTElement extends SimpleNode {
    private String symbol;

    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public ASTElement(int id) {
        super(id);
    }

    public ASTElement(SMARTSParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. * */
    public Object jjtAccept(SMARTSParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
