/* Generated By:JJTree: Do not edit this line. ASTImplicitHCount.java */

package org.openscience.cdk.smiles.smarts.parser;

public class ASTImplicitHCount extends SimpleNode {
    private int count;

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    public ASTImplicitHCount(int id) {
        super(id);
    }

    public ASTImplicitHCount(SMARTSParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. * */
    public Object jjtAccept(SMARTSParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
