/* Generated By:JJTree: Do not edit this line. ASTLogicalExpression.java */

package org.openscience.cdk.smiles.smarts.parser;

public class ASTLogicalExpression extends SimpleNode {
  public ASTLogicalExpression(int id) {
    super(id);
  }

  public ASTLogicalExpression(SMARTSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SMARTSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
