/* Generated By:JJTree: Do not edit this line. ASTLowAndBond.java */

package org.openscience.cdk.smiles.smarts.parser;

public class ASTLowAndBond extends SimpleNode {
  public ASTLowAndBond(int id) {
    super(id);
  }

  public ASTLowAndBond(SMARTSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SMARTSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
