/* Generated By:JJTree: Do not edit this line. ASTNotBond.java */

package org.openscience.cdk.smiles.smarts.parser;

public class ASTNotBond extends SimpleNode {
    private int type;

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public ASTNotBond(int id) {
        super(id);
    }

    public ASTNotBond(SMARTSParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. * */
    public Object jjtAccept(SMARTSParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
