/* Generated By:JJTree: Do not edit this line. ASTOrExpression.java */

package org.openscience.cdk.smiles.smarts.parser;

public class ASTOrExpression extends SimpleNode {
  public ASTOrExpression(int id) {
    super(id);
  }

  public ASTOrExpression(SMARTSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SMARTSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
