/* Generated By:JJTree: Do not edit this line. ASTOrBond.java */

package org.openscience.cdk.smiles.smarts.parser;

public class ASTOrBond extends SimpleNode {
  public ASTOrBond(int id) {
    super(id);
  }

  public ASTOrBond(SMARTSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SMARTSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
