/* Generated By:JJTree: Do not edit this line. ASTPrimitiveAtomExpression.java */

package org.openscience.cdk.smiles.smarts.parser;

public class ASTPrimitiveAtomExpression extends SimpleNode {
  public ASTPrimitiveAtomExpression(int id) {
    super(id);
  }

  public ASTPrimitiveAtomExpression(SMARTSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SMARTSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
