/* Generated By:JJTree: Do not edit this line. ASTRingConnectivity.java */

package org.openscience.cdk.smiles.smarts.parser;

public class ASTRingConnectivity extends SimpleNode {
    private int numOfConnection;

    public ASTRingConnectivity(int id) {
        super(id);
    }

    public ASTRingConnectivity(SMARTSParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. * */
    public Object jjtAccept(SMARTSParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public int getNumOfConnection() {
        return numOfConnection;
    }

    public void setNumOfConnection(int numOfConnection) {
        this.numOfConnection = numOfConnection;
    }

}
