/* Generated By:JJTree: Do not edit this line. ASTRingSize.java */

package org.openscience.cdk.smiles.smarts.parser;

public class ASTRingSize extends SimpleNode {
    private int size;

    public int getSize() {
        return size;
    }

    public void setSize(int size) {
        this.size = size;
    }

    public ASTRingSize(int id) {
        super(id);
    }

    public ASTRingSize(SMARTSParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. * */
    public Object jjtAccept(SMARTSParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
