/* Generated By:JJTree: Do not edit this line. ASTRingMembership.java */

package org.openscience.cdk.smiles.smarts.parser;

public class ASTRingMembership extends SimpleNode {
    private int numOfMembership;

    public int getNumOfMembership() {
        return numOfMembership;
    }

    public void setNumOfMembership(int numOfMembership) {
        this.numOfMembership = numOfMembership;
    }

    public ASTRingMembership(int id) {
        super(id);
    }

    public ASTRingMembership(SMARTSParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. * */
    public Object jjtAccept(SMARTSParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
