/* Generated By:JJTree: Do not edit this line. ASTSimpleBond.java */

package org.openscience.cdk.smiles.smarts.parser;

public class ASTSimpleBond extends SimpleNode {
    
    private int bondType;
    
  public int getBondType() {
        return bondType;
    }

    public void setBondType(int bondType) {
        this.bondType = bondType;
    }

public ASTSimpleBond(int id) {
    super(id);
  }

  public ASTSimpleBond(SMARTSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SMARTSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
