/* Generated By:JJTree: Do not edit this line. ASTTotalHCount.java */

package org.openscience.cdk.smiles.smarts.parser;

public class ASTTotalHCount extends SimpleNode {
    private int count;

    public ASTTotalHCount(int id) {
        super(id);
    }

    public ASTTotalHCount(SMARTSParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. * */
    public Object jjtAccept(SMARTSParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }
}
