/* Generated By:JJTree: Do not edit this line. D:/cygwin/home/djiao/workspace/cdk-mirror/src/org/openscience/cdk/smiles/smarts/parser\SMARTSParserTreeConstants.java */

package org.openscience.cdk.smiles.smarts.parser;

public interface SMARTSParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTREACTION = 1;
  public int JJTGROUP = 2;
  public int JJTSMARTS = 3;
  public int JJTBOND = 4;
  public int JJTLOWANDBOND = 5;
  public int JJTORBOND = 6;
  public int JJTEXPLICITHIGHANDBOND = 7;
  public int JJTIMPLICITHIGHANDBOND = 8;
  public int JJTNOTBOND = 9;
  public int JJTSIMPLEBOND = 10;
  public int JJTEXPLICITATOM = 11;
  public int JJTLOGICALEXPRESSION = 12;
  public int JJTLOWANDEXPRESSION = 13;
  public int JJTOREXPRESSION = 14;
  public int JJTEXPLICITHIGHANDEXPRESSION = 15;
  public int JJTIMPLICITHIGHANDEXPRESSION = 16;
  public int JJTNOTEXPRESSION = 17;
  public int JJTRECURSIVESMARTSEXPRESSION = 18;
  public int JJTVOID = 19;
  public int JJTTOTALHCOUNT = 20;
  public int JJTIMPLICITHCOUNT = 21;
  public int JJTDEGREE = 22;
  public int JJTATOMICNUMBER = 23;
  public int JJTCHARGE = 24;
  public int JJTRINGCONNECTIVITY = 25;
  public int JJTTOTALCONNECTIVITY = 26;
  public int JJTVALENCE = 27;
  public int JJTRINGMEMBERSHIP = 28;
  public int JJTRINGSIZE = 29;
  public int JJTALIPHATIC = 30;
  public int JJTAROMATIC = 31;
  public int JJTANYATOM = 32;
  public int JJTATOMICMASS = 33;
  public int JJTCHIRALITY = 34;
  public int JJTELEMENT = 35;


  public String[] jjtNodeName = {
    "Start",
    "Reaction",
    "Group",
    "Smarts",
    "Bond",
    "LowAndBond",
    "OrBond",
    "ExplicitHighAndBond",
    "ImplicitHighAndBond",
    "NotBond",
    "SimpleBond",
    "ExplicitAtom",
    "LogicalExpression",
    "LowAndExpression",
    "OrExpression",
    "ExplicitHighAndExpression",
    "ImplicitHighAndExpression",
    "NotExpression",
    "RecursiveSmartsExpression",
    "void",
    "TotalHCount",
    "ImplicitHCount",
    "Degree",
    "AtomicNumber",
    "Charge",
    "RingConnectivity",
    "TotalConnectivity",
    "Valence",
    "RingMembership",
    "RingSize",
    "Aliphatic",
    "Aromatic",
    "AnyAtom",
    "AtomicMass",
    "Chirality",
    "Element",
  };
}
