/* Generated By:JJTree: Do not edit this line. ASTNonCHHeavyAtom.java */

package org.openscience.cdk.smiles.smarts.parser;

public class ASTNonCHHeavyAtom extends SimpleNode {
  public ASTNonCHHeavyAtom(int id) {
    super(id);
  }

  public ASTNonCHHeavyAtom(SMARTSParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SMARTSParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
