/* Generated By:JJTree: Do not edit this line. SMARTSParserTreeConstants.java */

package org.openscience.cdk.smiles.smarts.parser;

/**
 * @author Dazhi Jiao
 * @cdk.module smarts
 * @cdk.svnrev  $Revision$
 * @cdk.keyword SMARTS
 */
public interface SMARTSParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTREACTION = 1;
  public int JJTGROUP = 2;
  public int JJTSMARTS = 3;
  public int JJTATOM = 4;
  public int JJTLOWANDBOND = 5;
  public int JJTORBOND = 6;
  public int JJTEXPLICITHIGHANDBOND = 7;
  public int JJTIMPLICITHIGHANDBOND = 8;
  public int JJTNOTBOND = 9;
  public int JJTSIMPLEBOND = 10;
  public int JJTEXPLICITATOM = 11;
  public int JJTLOWANDEXPRESSION = 12;
  public int JJTOREXPRESSION = 13;
  public int JJTEXPLICITHIGHANDEXPRESSION = 14;
  public int JJTIMPLICITHIGHANDEXPRESSION = 15;
  public int JJTNOTEXPRESSION = 16;
  public int JJTRECURSIVESMARTSEXPRESSION = 17;
  public int JJTVOID = 18;
  public int JJTTOTALHCOUNT = 19;
  public int JJTIMPLICITHCOUNT = 20;
  public int JJTEXPLICITCONNECTIVITY = 21;
  public int JJTATOMICNUMBER = 22;
  public int JJTCHARGE = 23;
  public int JJTRINGCONNECTIVITY = 24;
  public int JJTTOTALCONNECTIVITY = 25;
  public int JJTVALENCE = 26;
  public int JJTRINGMEMBERSHIP = 27;
  public int JJTSMALLESTRINGSIZE = 28;
  public int JJTALIPHATIC = 29;
  public int JJTAROMATIC = 30;
  public int JJTANYATOM = 31;
  public int JJTATOMICMASS = 32;
  public int JJTRINGIDENTIFIER = 33;
  public int JJTCHIRALITY = 34;
  public int JJTELEMENT = 35;


  public String[] jjtNodeName = {
    "Start",
    "Reaction",
    "Group",
    "Smarts",
    "Atom",
    "LowAndBond",
    "OrBond",
    "ExplicitHighAndBond",
    "ImplicitHighAndBond",
    "NotBond",
    "SimpleBond",
    "ExplicitAtom",
    "LowAndExpression",
    "OrExpression",
    "ExplicitHighAndExpression",
    "ImplicitHighAndExpression",
    "NotExpression",
    "RecursiveSmartsExpression",
    "void",
    "TotalHCount",
    "ImplicitHCount",
    "ExplicitConnectivity",
    "AtomicNumber",
    "Charge",
    "RingConnectivity",
    "TotalConnectivity",
    "Valence",
    "RingMembership",
    "SmallestRingSize",
    "Aliphatic",
    "Aromatic",
    "AnyAtom",
    "AtomicMass",
    "RingIdentifier",
    "Chirality",
    "Element",
  };
}
